/*

 LEVEL_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : level_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level_map_h_INCLUDE
#define __level_map_h_INCLUDE

#define level_mapWidth 20
#define level_mapHeight 18
#define level_mapBank 0

extern const unsigned char level_map[];

#endif

/* End of LEVEL_MAP.H */
