/*

 PLAYER_SPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __player_sprite_h_INCLUDE
#define __player_sprite_h_INCLUDE

/* Bank of tiles. */
#define player_spriteBank 0

/* Super Gameboy palette 0 */
#define player_spriteSGBPal0c0 6076
#define player_spriteSGBPal0c1 8935
#define player_spriteSGBPal0c2 6596
#define player_spriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define player_spriteSGBPal1c0 6076
#define player_spriteSGBPal1c1 8935
#define player_spriteSGBPal1c2 6596
#define player_spriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define player_spriteSGBPal2c0 6076
#define player_spriteSGBPal2c1 8935
#define player_spriteSGBPal2c2 6596
#define player_spriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define player_spriteSGBPal3c0 6076
#define player_spriteSGBPal3c1 8935
#define player_spriteSGBPal3c2 6596
#define player_spriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define player_spriteCGBPal0c0 6076
#define player_spriteCGBPal0c1 8935
#define player_spriteCGBPal0c2 6596
#define player_spriteCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define player_spriteCGBPal1c0 6076
#define player_spriteCGBPal1c1 8935
#define player_spriteCGBPal1c2 6596
#define player_spriteCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define player_spriteCGBPal2c0 6076
#define player_spriteCGBPal2c1 8935
#define player_spriteCGBPal2c2 6596
#define player_spriteCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define player_spriteCGBPal3c0 6076
#define player_spriteCGBPal3c1 8935
#define player_spriteCGBPal3c2 6596
#define player_spriteCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define player_spriteCGBPal4c0 6076
#define player_spriteCGBPal4c1 8935
#define player_spriteCGBPal4c2 6596
#define player_spriteCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define player_spriteCGBPal5c0 6076
#define player_spriteCGBPal5c1 8935
#define player_spriteCGBPal5c2 6596
#define player_spriteCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define player_spriteCGBPal6c0 6076
#define player_spriteCGBPal6c1 8935
#define player_spriteCGBPal6c2 6596
#define player_spriteCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define player_spriteCGBPal7c0 6076
#define player_spriteCGBPal7c1 8935
#define player_spriteCGBPal7c2 6596
#define player_spriteCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char player_sprite[];

#endif

/* End of PLAYER_SPRITE.H */
