/*

 PLAYER_SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char player_sprite[] =
{
  0x38,0x00,0x1E,0x60,0x40,0x3C,0x56,0x28,
  0x3C,0x00,0x10,0x00,0x38,0x00,0x3C,0x00,
  0x54,0x00,0x54,0x00,0x10,0x00,0x18,0x00,
  0x38,0x00,0x2C,0x00,0x64,0x00,0x46,0x00
};

/* End of PLAYER_SPRITE.C */
